kind: pipeline
type: docker
name: chess_CI_Pipeline

trigger:
  event:
    - push

steps:
  - name: build
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - cd src/ChessBuild/
      - dotnet restore ChessBuild.sln
      - dotnet build ChessBuild.sln -c Release --no-restore
      - dotnet publish ChessBuild.sln -c Release --no-restore -o $CI_PROJET_DIR/build/release
    depends_on: [clone]

  - name: tests
    image: mcr.microsoft.com/dotnet/sdk:8.0
    commands:
      - cd src/ChessBuild/
      - dotnet restore ChessBuild.sln
      - dotnet test ChessBuild.sln --no-restore
    depends_on: [build]

  - name: code-analysis
    image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet8-maui
    secrets: [ SECRET_SONAR_LOGIN ]
    settings:
    sonar_host: https://codefirst.iut.uca.fr/sonar/
    sonar_token:
      from_secrets: SECRET_SONAR_LOGIN

    when:
      branch:
        - master
      event:
        - push
        - pull_request

    # - name: code-inspection-linux-only
    #   image: hub.codefirst.iut.uca.fr/marc.chevaldonne/codefirst-dronesonarplugin-dotnet7
    #   secrets: [ CHESS_SECRET ]
    #   environment:
    #     sonart_host: https://codefirst.iut.uca.fr/sonar/
    #     sonar_token:
    #       from_secret: CHESS_SECRET

